In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd /content/drive/"MyDrive/ML"

/content/drive/MyDrive/ML

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
matches = pd.read_csv("matches.csv")

In [5]:
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [6]:
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  matches[col] = lbl_encoder.fit_transform(matches[col])

In [8]:
# Removing the seasons in which there are more than 8 teams on teams which are not consistent

In [9]:
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
59,60,IPL-2008,2,18-04-2008,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,1,normal,0,Kolkata Knight Riders,140,0,BB McCullum,17,Asad Rauf,RE Koertzen,NaN
60,61,IPL-2008,7,19-04-2008,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0,normal,0,Chennai Super Kings,33,0,MEK Hussey,27,MR Benson,SL Shastri,NaN
61,62,IPL-2008,10,19-04-2008,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,0,normal,0,Delhi Daredevils,0,9,MF Maharoof,9,Aleem Dar,GA Pratapkumar,NaN
62,63,IPL-2008,24,20-04-2008,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,0,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,40,SJ Davis,DJ Harper,NaN
63,64,IPL-2008,22,20-04-2008,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,0,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,8,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,24,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,1,normal,0,Mumbai Indians,0,9,HH Pandya,40,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,8,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,0,normal,0,Mumbai Indians,0,6,AS Yadav,18,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,32,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,1,normal,0,Delhi Capitals,0,2,RR Pant,0,NaN,NaN,NaN
754,11414,IPL-2019,32,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,1,normal,0,Chennai Super Kings,0,6,F du Plessis,0,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,15,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,0,normal,0,Mumbai Indians,1,0,JJ Bumrah,29,Nitin Menon,Ian Gould,Nigel Llong

In [10]:
encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}
matches.replace(encoded_dict,inplace=True)

In [11]:
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
59,60,IPL-2008,2,18-04-2008,3,4,4,1,normal,0,3,140,0,BB McCullum,17,Asad Rauf,RE Koertzen,NaN
60,61,IPL-2008,7,19-04-2008,2,5,2,0,normal,0,2,33,0,MEK Hussey,27,MR Benson,SL Shastri,NaN
61,62,IPL-2008,10,19-04-2008,6,7,6,0,normal,0,7,0,9,MF Maharoof,9,Aleem Dar,GA Pratapkumar,NaN
62,63,IPL-2008,24,20-04-2008,1,4,1,0,normal,0,4,0,5,MV Boucher,40,SJ Davis,DJ Harper,NaN
63,64,IPL-2008,22,20-04-2008,8,3,8,0,normal,0,3,0,5,DJ Hussey,8,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,24,05-05-2019,3,1,1,1,normal,0,1,0,9,HH Pandya,40,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,8,07-05-2019,2,1,2,0,normal,0,1,0,6,AS Yadav,18,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,32,08-05-2019,8,7,7,1,normal,0,7,0,2,RR Pant,0,NaN,NaN,NaN
754,11414,IPL-2019,32,10-05-2019,7,2,2,1,normal,0,2,0,6,F du Plessis,0,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,15,12-05-2019,1,2,1,0,normal,0,1,1,0,JJ Bumrah,29,Nitin Menon,Ian Gould,Nigel Llong

In [12]:
# Overall attempt

In [13]:
testing_dataset = matches[matches['Season']=='IPL-2019']
training_dataset = matches[matches['Season']!='IPL-2019']

In [14]:
train_x = training_dataset[['team1' , 'team2' , 'city' , 'toss_decision', 'toss_winner' , 'venue' ]]
train_y = training_dataset['winner']
test_x = testing_dataset[['team1' , 'team2' , 'city' , 'toss_decision', 'toss_winner' , 'venue' ]]
test_y = testing_dataset['winner']
train_x

     team1  team2  city  toss_decision  toss_winner  venue
59       3      4     2              1            4     17
60       2      5     7              0            2     27
61       6      7    10              0            6      9
62       1      4    24              0            1     40
63       8      3    22              0            8      8
..     ...    ...   ...            ...          ...    ...
691      5      2    27              1            2     21
692      8      2    24              1            2     40
693      3      6    22              1            6      8
694      8      3    22              1            3      8
695      8      2    24              1            2     40

[294 rows x 6 columns]

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=5000)
logreg.fit(train_x,train_y)
y_predict = logreg.predict(test_x)
#print(y_predict)
print("Accuracy:",metrics.accuracy_score(test_y, y_predict))

Accuracy: 0.3333333333333333

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, y_predict)

array([[8, 0, 0, 0, 0, 2, 1, 0, 0],
       [0, 4, 3, 0, 2, 1, 0, 0, 0],
       [0, 2, 3, 0, 1, 0, 0, 0, 0],
       [0, 1, 2, 0, 2, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 3, 0],
       [2, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 2, 5, 0],
       [0, 0, 0, 0, 2, 1, 1, 2, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(train_x,train_y)
y_predict = rf.predict(test_x)
print("Accuracy:",metrics.accuracy_score(test_y, y_predict))
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, y_predict)

Accuracy: 0.5666666666666667

array([[7, 1, 0, 0, 1, 0, 1, 1, 0],
       [0, 8, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 3, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 3, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 2, 1, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [1, 0, 2, 0, 0, 2, 4, 1, 0],
       [0, 1, 0, 0, 1, 0, 1, 3, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [18]:
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,8):

  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(train_x,train_y)
  predicted= model.predict(test_x)
  print("Accuracy:",metrics.accuracy_score(test_y, predicted))
  from sklearn.metrics import confusion_matrix
  print(confusion_matrix(test_y, y_predict))

Accuracy: 0.4
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]
Accuracy: 0.4166666666666667
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]
Accuracy: 0.4166666666666667
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]
Accuracy: 0.35
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]
Accuracy: 0.45
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]
Accuracy: 0.45
[[7 1 0 0 1 0 1 1 0]
 [0 8 0 0 1 0 1 0 0]
 [1 0 3 0 1 0 0 1 0]
 [0 1 1 3 0 0 0 0 0]
 [1 1 0 0 1 2 1 0 0]
 [0 0 0 0 0 5 0 0 0]
 [1 0 2 0 0 2 4 1 0]
 [0 1 0 0 1 0 1 3 0]
 [0 0 0 0 0 1 0 0 0]]

In [19]:
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(train_x,train_y)
y_pred = svc.predict(test_x)
print(confusion_matrix(test_y, y_pred))
print("Linear SVM Acuracy:  ",accuracy_score(test_y,y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.005,C=C).fit(train_x,train_y)
y_pred = rbf_svc.predict(test_x)
print(confusion_matrix(test_y, y_pred))
print("RBF SVM Acuracy:",accuracy_score(test_y,y_pred))
poly_svc = svm.SVC(kernel='poly',degree=3,C=C).fit(train_x,train_y)
y_pred = poly_svc.predict(test_x)
print("Polynmial SVM Acuracy:",accuracy_score(test_y,y_pred))
print(confusion_matrix(test_y, y_pred))

[[7 3 0 0 0 0 1 0 0]
 [0 4 3 0 2 1 0 0 0]
 [1 1 2 0 2 0 0 0 0]
 [0 1 2 2 0 0 0 0 0]
 [0 2 0 0 0 1 0 3 0]
 [2 0 1 0 0 1 0 1 0]
 [0 0 1 0 1 0 3 5 0]
 [0 1 0 0 2 0 0 3 0]
 [0 0 0 0 0 1 0 0 0]]
Linear SVM Acuracy:   0.36666666666666664
[[5 4 0 0 0 1 0 1 0]
 [0 5 1 1 0 1 1 1 0]
 [0 1 4 0 0 1 0 0 0]
 [0 1 2 2 0 0 0 0 0]
 [0 1 4 0 0 1 0 0 0]
 [1 0 1 0 0 3 0 0 0]
 [1 0 1 1 0 1 4 2 0]
 [0 0 0 0 0 1 1 4 0]
 [0 0 0 1 0 0 0 0 0]]
RBF SVM Acuracy: 0.45
Polynmial SVM Acuracy: 0.3
[[4 5 0 0 1 0 1 0 0]
 [0 8 1 0 1 0 0 0 0]
 [0 3 2 0 1 0 0 0 0]
 [0 3 2 0 0 0 0 0 0]
 [0 2 2 0 0 1 0 1 0]
 [1 0 1 0 0 1 1 1 0]
 [0 5 1 0 1 0 0 3 0]
 [0 0 0 1 1 0 1 3 0]
 [0 1 0 0 0 0 0 0 0]]

In [20]:
#  For mumbai indians
data = matches

In [21]:
data.winner.replace({2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},inplace=True)
data

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
59,60,IPL-2008,2,18-04-2008,3,4,4,1,normal,0,0,140,0,BB McCullum,17,Asad Rauf,RE Koertzen,NaN
60,61,IPL-2008,7,19-04-2008,2,5,2,0,normal,0,0,33,0,MEK Hussey,27,MR Benson,SL Shastri,NaN
61,62,IPL-2008,10,19-04-2008,6,7,6,0,normal,0,0,0,9,MF Maharoof,9,Aleem Dar,GA Pratapkumar,NaN
62,63,IPL-2008,24,20-04-2008,1,4,1,0,normal,0,0,0,5,MV Boucher,40,SJ Davis,DJ Harper,NaN
63,64,IPL-2008,22,20-04-2008,8,3,8,0,normal,0,0,0,5,DJ Hussey,8,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,24,05-05-2019,3,1,1,1,normal,0,1,0,9,HH Pandya,40,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,8,07-05-2019,2,1,2,0,normal,0,1,0,6,AS Yadav,18,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,32,08-05-2019,8,7,7,1,normal,0,0,0,2,RR Pant,0,NaN,NaN,NaN
754,11414,IPL-2019,32,10-05-2019,7,2,2,1,normal,0,0,0,6,F du Plessis,0,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,15,12-05-2019,1,2,1,0,normal,0,1,1,0,JJ Bumrah,29,Nitin Menon,Ian Gould,Nigel Llong

In [22]:
from sklearn.preprocessing import LabelEncoder
ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  print(lbl_encoder.classes_)
data

[ 0  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 20 22 23 24 26 27
 28 30 31 32]
[0 1]
[ 0  1  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18 19 20 21 23 24 25 26
 27 28 29 30 32 33 34 35 36 38 40]

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
59,60,IPL-2008,2,18-04-2008,3,4,4,1,normal,0,0,140,0,BB McCullum,15,Asad Rauf,RE Koertzen,NaN
60,61,IPL-2008,7,19-04-2008,2,5,2,0,normal,0,0,33,0,MEK Hussey,24,MR Benson,SL Shastri,NaN
61,62,IPL-2008,10,19-04-2008,6,7,6,0,normal,0,0,0,9,MF Maharoof,9,Aleem Dar,GA Pratapkumar,NaN
62,63,IPL-2008,21,20-04-2008,1,4,1,0,normal,0,0,0,5,MV Boucher,34,SJ Davis,DJ Harper,NaN
63,64,IPL-2008,19,20-04-2008,8,3,8,0,normal,0,0,0,5,DJ Hussey,8,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,21,05-05-2019,3,1,1,1,normal,0,1,0,9,HH Pandya,34,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,8,07-05-2019,2,1,2,0,normal,0,1,0,6,AS Yadav,16,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,27,08-05-2019,8,7,7,1,normal,0,0,0,2,RR Pant,0,NaN,NaN,NaN
754,11414,IPL-2019,27,10-05-2019,7,2,2,1,normal,0,0,0,6,F du Plessis,0,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,14,12-05-2019,1,2,1,0,normal,0,1,1,0,JJ Bumrah,26,Nitin Menon,Ian Gould,Nigel Llong

In [23]:
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=100)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_train)
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_pred)

Accuracy: 0.8983050847457628

array([[299,   9],
       [ 27,  19]])

In [25]:
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):

  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_train)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_train, predicted))
  print(confusion_matrix(y_train, y_pred))

 K =   2  Accuracy: 0.9209039548022598
[[299   9]
 [ 27  19]]
 K =   3  Accuracy: 0.923728813559322
[[299   9]
 [ 27  19]]
 K =   4  Accuracy: 0.9011299435028248
[[299   9]
 [ 27  19]]
 K =   5  Accuracy: 0.8898305084745762
[[299   9]
 [ 27  19]]
 K =   6  Accuracy: 0.8954802259887006
[[299   9]
 [ 27  19]]
 K =   7  Accuracy: 0.8813559322033898
[[299   9]
 [ 27  19]]
 K =   8  Accuracy: 0.8785310734463276
[[299   9]
 [ 27  19]]
 K =   9  Accuracy: 0.8785310734463276
[[299   9]
 [ 27  19]]
 K =   10  Accuracy: 0.8870056497175142
[[299   9]
 [ 27  19]]
 K =   11  Accuracy: 0.8813559322033898
[[299   9]
 [ 27  19]]

In [26]:
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_train)
print("Linear SVM Acuracy:  ",accuracy_score(y_train,y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_train)
print("RBF SVM Acuracy:",accuracy_score(y_train,y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_train)
  print("Polynmial SVM Acuracy:",accuracy_score(y_train,y_pred))

Linear SVM Acuracy:   0.9011299435028248
RBF SVM Acuracy: 0.9491525423728814
Polynmial SVM Acuracy: 0.8898305084745762
Polynmial SVM Acuracy: 0.8926553672316384
Polynmial SVM Acuracy: 0.903954802259887
Polynmial SVM Acuracy: 0.9124293785310734

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_train)
print("Accuracy:",metrics.accuracy_score(y_train, y_predict))
confusion_matrix(y_train, y_pred)

Accuracy: 0.9745762711864406

array([[302,   6],
       [ 25,  21]])

In [28]:
# Mumbai Indians

In [29]:
matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==1] 
match2 = matches[matches['team2']==1]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:1,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.5
[[4 4]
 [5 5]]


 KNN:

 K =   2  Accuracy: 0.7222222222222222
[[4 4]
 [5 5]]
 K =   3  Accuracy: 0.6666666666666666
[[4 4]
 [5 5]]
 K =   4  Accuracy: 0.6666666666666666
[[4 4]
 [5 5]]
 K =   5  Accuracy: 0.5
[[4 4]
 [5 5]]
 K =   6  Accuracy: 0.5
[[4 4]
 [5 5]]
 K =   7  Accuracy: 0.4444444444444444
[[4 4]
 [5 5]]
 K =   8  Accuracy: 0.5555555555555556
[[4 4]
 [5 5]]
 K =   9  Accuracy: 0.3888888888888889
[[4 4]
 [5 5]]
 K =   10  Accuracy: 0.4444444444444444
[[4 4]
 [5 5]]
 K =   11  Accuracy: 0.5
[[4 4]
 [5 5]]


 SVM :

Linear SVM Acuracy:   0.5
[[2 6]
 [3 7]]
RBF SVM Acuracy: 1.0
[[ 8  0]
 [ 0 10]]
Polynmial SVM Acuracy for degree  4  is :  0.4444444444444444
[[5 3]
 [7 3]]
Polynmial SVM Acuracy for degree  5  is :  0.5555555555555556
[[7 1]
 [7 3]]
Polynmial SVM Acuracy for degree  6  is :  0.5
[[7 1]
 [8 2]]
Polynmial SVM Acuracy for degree  7  is :  0.5
[[7 1]
 [8 2]]


 Random Forest :

Accuracy: 1.0
[[7 1]
 [8 2]]

In [30]:
#Chennai Super kings

In [31]:
matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==2] 
match2 = matches[matches['team2']==2]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:1,3:0,4:0,5:0,6:0,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.7
[[ 1  6]
 [ 0 13]]


 KNN:

 K =   2  Accuracy: 0.8
[[ 1  6]
 [ 0 13]]
 K =   3  Accuracy: 0.85
[[ 1  6]
 [ 0 13]]
 K =   4  Accuracy: 0.8
[[ 1  6]
 [ 0 13]]
 K =   5  Accuracy: 0.75
[[ 1  6]
 [ 0 13]]
 K =   6  Accuracy: 0.7
[[ 1  6]
 [ 0 13]]
 K =   7  Accuracy: 0.7
[[ 1  6]
 [ 0 13]]
 K =   8  Accuracy: 0.7
[[ 1  6]
 [ 0 13]]
 K =   9  Accuracy: 0.7
[[ 1  6]
 [ 0 13]]
 K =   10  Accuracy: 0.65
[[ 1  6]
 [ 0 13]]
 K =   11  Accuracy: 0.65
[[ 1  6]
 [ 0 13]]


 SVM :

Linear SVM Acuracy:   0.65
[[ 0  7]
 [ 0 13]]
RBF SVM Acuracy: 0.95
[[ 6  1]
 [ 0 13]]
Polynmial SVM Acuracy for degree  4  is :  0.7
[[ 1  6]
 [ 0 13]]
Polynmial SVM Acuracy for degree  5  is :  0.75
[[ 2  5]
 [ 0 13]]
Polynmial SVM Acuracy for degree  6  is :  0.85
[[ 4  3]
 [ 0 13]]
Polynmial SVM Acuracy for degree  7  is :  0.85
[[ 4  3]
 [ 0 13]]


 Random Forest :

Accuracy: 0.95
[[ 4  3]
 [ 0 13]]

In [32]:
# Kolkata Night riders
matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==3] 
match2 = matches[matches['team2']==3]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:1,4:0,5:0,6:0,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.6470588235294118
[[6 3]
 [3 5]]


 KNN:

 K =   2  Accuracy: 0.7058823529411765
[[6 3]
 [3 5]]
 K =   3  Accuracy: 0.7058823529411765
[[6 3]
 [3 5]]
 K =   4  Accuracy: 0.5294117647058824
[[6 3]
 [3 5]]
 K =   5  Accuracy: 0.6470588235294118
[[6 3]
 [3 5]]
 K =   6  Accuracy: 0.5294117647058824
[[6 3]
 [3 5]]
 K =   7  Accuracy: 0.47058823529411764
[[6 3]
 [3 5]]
 K =   8  Accuracy: 0.47058823529411764
[[6 3]
 [3 5]]
 K =   9  Accuracy: 0.47058823529411764
[[6 3]
 [3 5]]
 K =   10  Accuracy: 0.4117647058823529
[[6 3]
 [3 5]]
 K =   11  Accuracy: 0.47058823529411764
[[6 3]
 [3 5]]


 SVM :

Linear SVM Acuracy:   0.5294117647058824
[[4 5]
 [3 5]]
RBF SVM Acuracy: 0.8235294117647058
[[8 1]
 [2 6]]
Polynmial SVM Acuracy for degree  4  is :  0.5882352941176471
[[3 6]
 [1 7]]
Polynmial SVM Acuracy for degree  5  is :  0.7058823529411765
[[4 5]
 [0 8]]
Polynmial SVM Acuracy for degree  6  is :  0.6470588235294118
[[4 5]
 [1 7]]
Polynmial SVM Acuracy for degree  7  is :  0.6470588235294118
[[4 5]
 [1 7]]


 Random Forest :

Accuracy: 0.8235294117647058
[[4 5]
 [1 7]]

In [33]:
# Royal Challangers banglore

matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==4] 
match2 = matches[matches['team2']==4]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:0,4:1,5:0,6:0,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.5555555555555556
[[8 3]
 [5 2]]


 KNN:

 K =   2  Accuracy: 0.7777777777777778
[[8 3]
 [5 2]]
 K =   3  Accuracy: 0.6666666666666666
[[8 3]
 [5 2]]
 K =   4  Accuracy: 0.6666666666666666
[[8 3]
 [5 2]]
 K =   5  Accuracy: 0.7222222222222222
[[8 3]
 [5 2]]
 K =   6  Accuracy: 0.5555555555555556
[[8 3]
 [5 2]]
 K =   7  Accuracy: 0.4444444444444444
[[8 3]
 [5 2]]
 K =   8  Accuracy: 0.6111111111111112
[[8 3]
 [5 2]]
 K =   9  Accuracy: 0.5555555555555556
[[8 3]
 [5 2]]
 K =   10  Accuracy: 0.5
[[8 3]
 [5 2]]
 K =   11  Accuracy: 0.5555555555555556
[[8 3]
 [5 2]]


 SVM :

Linear SVM Acuracy:   0.6111111111111112
[[11  0]
 [ 7  0]]
RBF SVM Acuracy: 0.8888888888888888
[[10  1]
 [ 1  6]]
Polynmial SVM Acuracy for degree  4  is :  0.6666666666666666
[[10  1]
 [ 5  2]]
Polynmial SVM Acuracy for degree  5  is :  0.6666666666666666
[[10  1]
 [ 5  2]]
Polynmial SVM Acuracy for degree  6  is :  0.7222222222222222
[[11  0]
 [ 5  2]]
Polynmial SVM Acuracy for degree  7  is :  0.7222222222222222
[[10  1]
 [ 4  3]]


 Random Forest :

Accuracy: 0.8888888888888888
[[10  1]
 [ 4  3]]

In [34]:
# Kings XI Punjab

matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==5] 
match2 = matches[matches['team2']==5]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:0,4:0,5:1,6:0,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.6666666666666666
[[6 3]
 [3 6]]


 KNN:

 K =   2  Accuracy: 0.7777777777777778
[[6 3]
 [3 6]]
 K =   3  Accuracy: 0.8333333333333334
[[6 3]
 [3 6]]
 K =   4  Accuracy: 0.7777777777777778
[[6 3]
 [3 6]]
 K =   5  Accuracy: 0.7222222222222222
[[6 3]
 [3 6]]
 K =   6  Accuracy: 0.7777777777777778
[[6 3]
 [3 6]]
 K =   7  Accuracy: 0.7777777777777778
[[6 3]
 [3 6]]
 K =   8  Accuracy: 0.7777777777777778
[[6 3]
 [3 6]]
 K =   9  Accuracy: 0.6666666666666666
[[6 3]
 [3 6]]
 K =   10  Accuracy: 0.6111111111111112
[[6 3]
 [3 6]]
 K =   11  Accuracy: 0.5555555555555556
[[6 3]
 [3 6]]


 SVM :

Linear SVM Acuracy:   0.6111111111111112
[[5 4]
 [3 6]]
RBF SVM Acuracy: 0.9444444444444444
[[9 0]
 [1 8]]
Polynmial SVM Acuracy for degree  4  is :  0.6111111111111112
[[7 2]
 [5 4]]
Polynmial SVM Acuracy for degree  5  is :  0.6666666666666666
[[8 1]
 [5 4]]
Polynmial SVM Acuracy for degree  6  is :  0.7222222222222222
[[8 1]
 [4 5]]
Polynmial SVM Acuracy for degree  7  is :  0.7222222222222222
[[9 0]
 [5 4]]


 Random Forest :

Accuracy: 0.8888888888888888
[[9 0]
 [5 4]]

In [35]:
# Rajasthan Royals

matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==6] 
match2 = matches[matches['team2']==6]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:0,4:0,5:0,6:1,7:0,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.3888888888888889
[[3 7]
 [4 4]]


 KNN:

 K =   2  Accuracy: 0.7777777777777778
[[3 7]
 [4 4]]
 K =   3  Accuracy: 0.8333333333333334
[[3 7]
 [4 4]]
 K =   4  Accuracy: 0.8333333333333334
[[3 7]
 [4 4]]
 K =   5  Accuracy: 0.7222222222222222
[[3 7]
 [4 4]]
 K =   6  Accuracy: 0.7222222222222222
[[3 7]
 [4 4]]
 K =   7  Accuracy: 0.7777777777777778
[[3 7]
 [4 4]]
 K =   8  Accuracy: 0.6666666666666666
[[3 7]
 [4 4]]
 K =   9  Accuracy: 0.7222222222222222
[[3 7]
 [4 4]]
 K =   10  Accuracy: 0.7222222222222222
[[3 7]
 [4 4]]
 K =   11  Accuracy: 0.6111111111111112
[[3 7]
 [4 4]]


 SVM :

Linear SVM Acuracy:   0.5
[[4 6]
 [3 5]]
RBF SVM Acuracy: 0.9444444444444444
[[9 1]
 [0 8]]
Polynmial SVM Acuracy for degree  4  is :  0.6666666666666666
[[7 3]
 [3 5]]
Polynmial SVM Acuracy for degree  5  is :  0.7777777777777778
[[9 1]
 [3 5]]
Polynmial SVM Acuracy for degree  6  is :  0.7777777777777778
[[9 1]
 [3 5]]
Polynmial SVM Acuracy for degree  7  is :  0.7777777777777778
[[9 1]
 [3 5]]


 Random Forest :

Accuracy: 0.9444444444444444
[[9 1]
 [3 5]]

In [36]:
# Delhi Capitals

matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==7] 
match2 = matches[matches['team2']==7]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:0,4:0,5:0,6:0,7:1,8:0,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.6666666666666666
[[11  1]
 [ 5  1]]


 KNN:

 K =   2  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]
 K =   3  Accuracy: 0.8333333333333334
[[11  1]
 [ 5  1]]
 K =   4  Accuracy: 0.6666666666666666
[[11  1]
 [ 5  1]]
 K =   5  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]
 K =   6  Accuracy: 0.6666666666666666
[[11  1]
 [ 5  1]]
 K =   7  Accuracy: 0.6666666666666666
[[11  1]
 [ 5  1]]
 K =   8  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]
 K =   9  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]
 K =   10  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]
 K =   11  Accuracy: 0.7222222222222222
[[11  1]
 [ 5  1]]


 SVM :

Linear SVM Acuracy:   0.7222222222222222
[[12  0]
 [ 5  1]]
RBF SVM Acuracy: 0.9444444444444444
[[12  0]
 [ 1  5]]
Polynmial SVM Acuracy for degree  4  is :  0.7222222222222222
[[12  0]
 [ 5  1]]
Polynmial SVM Acuracy for degree  5  is :  0.8333333333333334
[[12  0]
 [ 3  3]]
Polynmial SVM Acuracy for degree  6  is :  0.8333333333333334
[[12  0]
 [ 3  3]]
Polynmial SVM Acuracy for degree  7  is :  0.9444444444444444
[[12  0]
 [ 1  5]]


 Random Forest :

Accuracy: 0.9444444444444444
[[12  0]
 [ 1  5]]

In [37]:
# Sunrisers Hyderabad
matches = pd.read_csv("matches.csv")
matches[matches['winner'].isnull() == True]
matches['winner'].fillna('No result',inplace=True)
matches[matches['city'].isnull() == True]
matches['city'].fillna('Dubai',inplace=True)
matches = matches[matches['Season']!='IPL-2010']
matches = matches[matches['Season']!='IPL-2011']
matches = matches[matches['Season']!='IPL-2012']
matches = matches[matches['Season']!='IPL-2013']
matches = matches[matches['Season']!='IPL-2016']
matches = matches[matches['Season']!='IPL-2017']

encoded_team = {
    'Mumbai Indians' : 1,
    'Chennai Super Kings' : 2,
    'Kolkata Knight Riders' : 3,
    'Royal Challengers Bangalore' : 4,
    'Kings XI Punjab'  : 5,
    'Rajasthan Royals'  : 6,
    'Delhi Daredevils' : 7,
    'Sunrisers Hyderabad' : 8,
    'Deccan Chargers' : 8,
    'Delhi Capitals' : 7,
    'No result' : 9
}

encoded_dict = {
    'team1' : encoded_team,
    'team2' : encoded_team,
    'toss_winner' : encoded_team,
    'winner' : encoded_team
}

matches.replace(encoded_dict,inplace=True)

match1 = matches[matches['team1']==8] 
match2 = matches[matches['team2']==8]
data = match1.append(match2)
#data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ls = ['city','toss_decision','venue']
lbl_encoder = LabelEncoder()
for col in ls:
  data[col] = lbl_encoder.fit_transform(data[col])
  #print(lbl_encoder.classes_)
data.winner.replace({1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:1,9:0},inplace=True)
data
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.20, random_state=0)
x_train = data[['team1' , 'team2','city','toss_decision','toss_winner','venue']]
y_train = data['winner']

# Logistic regression
print('Logistic Regression : \n')
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty="none",max_iter=50)
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

#KNN
print('\n\n KNN: \n')
from sklearn.neighbors import KNeighborsClassifier
for i in range (2,12):
  model = KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  predicted= model.predict(x_test)
  print(" K =  ",i , end = "  ")
  print("Accuracy:",metrics.accuracy_score(y_test, predicted))
  print(confusion_matrix(y_test, y_pred))

#SVM
print("\n\n SVM :  \n")
C=1
from sklearn import svm
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svc = svm.SVC(kernel='linear',C=C).fit(x_train,y_train)
y_pred = svc.predict(x_test)
print("Linear SVM Acuracy:  ",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
rbf_svc = svm.SVC(kernel='rbf',gamma=0.5,C=C).fit(x_train,y_train)
y_pred = rbf_svc.predict(x_test)
print("RBF SVM Acuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
for i in range(4,8):
  poly_svc = svm.SVC(kernel='poly',degree=i,C=C).fit(x_train,y_train)
  y_pred = poly_svc.predict(x_test)
  print("Polynmial SVM Acuracy for degree ",i," is : ",accuracy_score(y_test,y_pred))
  print(confusion_matrix(y_test, y_pred))


# Random forest
print("\n\n Random Forest : \n")
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
y_predict = rf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_pred))

Logistic Regression :

Accuracy: 0.8333333333333334
[[13  1]
 [ 2  2]]


 KNN:

 K =   2  Accuracy: 0.8888888888888888
[[13  1]
 [ 2  2]]
 K =   3  Accuracy: 0.8888888888888888
[[13  1]
 [ 2  2]]
 K =   4  Accuracy: 0.8333333333333334
[[13  1]
 [ 2  2]]
 K =   5  Accuracy: 0.7777777777777778
[[13  1]
 [ 2  2]]
 K =   6  Accuracy: 0.7777777777777778
[[13  1]
 [ 2  2]]
 K =   7  Accuracy: 0.8333333333333334
[[13  1]
 [ 2  2]]
 K =   8  Accuracy: 0.7222222222222222
[[13  1]
 [ 2  2]]
 K =   9  Accuracy: 0.7222222222222222
[[13  1]
 [ 2  2]]
 K =   10  Accuracy: 0.6111111111111112
[[13  1]
 [ 2  2]]
 K =   11  Accuracy: 0.6666666666666666
[[13  1]
 [ 2  2]]


 SVM :

Linear SVM Acuracy:   0.7777777777777778
[[13  1]
 [ 3  1]]
RBF SVM Acuracy: 1.0
[[14  0]
 [ 0  4]]
Polynmial SVM Acuracy for degree  4  is :  0.7222222222222222
[[11  3]
 [ 2  2]]
Polynmial SVM Acuracy for degree  5  is :  0.7222222222222222
[[11  3]
 [ 2  2]]
Polynmial SVM Acuracy for degree  6  is :  0.7777777777777778
[[12  2]
 [ 2  2]]
Polynmial SVM Acuracy for degree  7  is :  0.8888888888888888
[[12  2]
 [ 0  4]]


 Random Forest :

Accuracy: 1.0
[[12  2]
 [ 0  4]]